### PR TITLE
[Statistic] Mark current date on "Finds for Each Day of the Year" statistic

### PR DESCRIPTION
**Pull request by sdennler**
Mark current date on Finds for Each Day of the Year statistic.

### CODE REVIEW

**Review by 2Abendsegler — CHANGES_REQUESTED** [review]
Hallo,

danke für deine Arbeit.

Ich habe mir die Entwicklung kurz angesehen, scheint zu funktionieren. Es wird der aktuelle Tag gekennzeichnet. Kannst du mir bitte kurz erklären wie diese Kennzeichnung dir behilflich ist?

grafik

Der Parameter `settings_log_statistic` wird für die Log Statistik verwendet. Für deine Entwicklung im Bereich "Finds for Each Day of the Year" sollte ein neuer Parameter verwendet werden.

**Comment by sdennler** [comment]
Thanks for the feedback! On 90 out of 100 times when I look at the statistic page it is to see how many caches I need to reach my goal today or in the upcoming days. To do so it is very helpful to have the current day marked. I use [this feature](https://gist.github.com/sdennler/b11228c0f289c62fe640b3aac91198f9) since a while and wanted to share it here.

I misunderstood the use of the variable `settings_log_statistic`. Do you think a dedicated setting is needed for this or can it be always enabled?

**Comment by 2Abendsegler** [comment]
Yes, you are right, because it is not error prone it can be always enabled. So, please remove the parameter `settings_log_statistic`. We will then integrate your extension into the next version.
Thanks

**Review by 2Abendsegler — APPROVED** [review]
Thanks

**Pull request merged**
