### PR TITLE
Correct user name to global_me

### PR DESCRIPTION
**Pull request by Vylda**
in D/T matrix are bad anchors. It is because the span element as text is in global_me variable

### CODE REVIEW

**Comment by Ruko2010** [comment]
Hi @Vylda
Nice to see, that you managed it to create the pull request. I'm not sure what exactly the problem ist? Can you please provide some more informations? At least the page where the error occurs. 
Maybe it is a good idea to create a bug-issue and fill out the form, so we can reproduce the problem and then evaluate your solution. You can use this link to do so: https://github.com/2Abendsegler/GClh/issues/new?template=Bug_report.md

**Comment by Vylda** [comment]
Hi @Ruko2010 .

Try click to D/T matrix number (Generate cache search links with radius im Settings). You see bad URL: https://www.geocaching.com/play/search?origin=N 49° 10.489 E 016° 33.510&radius=200km&t=4&d=4.5&nfb[0]=<span class="cache-count"></span>&f=2&o=2&nfb[1]=GClh#GClhMap. It doesn't wor, server return 500 (because bad URL).

Error is in nfb[0] query string attribute. It must be your name.

**Comment by Ruko2010** [comment]
@Vylda Problem solved?

**Comment by Vylda** [comment]
It looks that it is all right...

**Pull request closed without merging**
