### PR TITLE
Merge  #819 (improvement) Link to personal Ignore List at section List in sidebar of the new dashboard

### PR DESCRIPTION
**Pull request by CachingFoX**

### CODE REVIEW

**Comment by CachingFoX** [comment]
I will check it.

I merge the last updates from collector into my issue-819 branch and the link works for me. I check it with Windows and Firefox. I will check it with Windows and Chrome soon.

**Comment by CachingFoX** [comment]
I added an alert if the Igore List link can not be found.
The Ignore List will only embedded for PMs

Known bug: `GM_xmlhttpRequest` doesn't work well with the private mode. If in private mode another user logged into geocaching.com, GM_xmlhttpRequest() sends the authentication for the user which logged in in normal mode.

**Comment by Ruko2010** [comment]
Maybe the Problem was, that I do not have an ignore list (i think). Have you tested this case?

**Comment by Ruko2010** [comment]
Works for me now! Great 😃

**Pull request merged**
