### PR TITLE
Improve new dashboard css (little bit narrower elements)

### PR DESCRIPTION
**Pull request by DrakMrak**
small change in css

### CODE REVIEW

**Comment by DrakMrak** [comment]
Hi

I understand :) that not all peopl likes everything... but I try makes important changes...
Ok... I'll try to think about the "New Dashboard" as a whole and make more adjustments, with the ability to turn it on and off in setting. I will look at the other parts you have designed me.

I had my script to change the elements of Dashboard and there is more code  but not all are ideal therefore I have just given only three small details... others I have to change it.

Discussion on CZ forum about GClh already exists :) because I like GClh for a long time (since the time of the original author). It will be good to open the issue about design modifications for new Dashboard...

Then I also entering into your job and do not want to act as a distracting element. In addition, I'am not very good in English and no German ;)

I hope this is understandable ;)

**Comment by DrakMrak** [comment]
> (I have already made a change, just so you do not double them. Our own round switches now rotate also 180 degrees.)
I did not work on it, but I'd like to see how it works :)

**Comment by 2Abendsegler** [comment]
Hi, 

you are not a distracting element! We are learning, to develop with javascript, to develop in a group of developers and to do it for a group of people which makes in the most cases no requirements and which have all their own personal thinking about every little point. I'm learning also. ;)

If you want to do a compacter layout for the new dashboard, like it is for example done for the bookmark lists, we do not need a lot of switches. We can offer the compact layout with one switch. You can pack everything you want, even what matters to you. And then people can use it or can let it. :)

I can not observe if your english is not so good. But if it is, then we are already two, hahaha. :D

Merry christmas to you and your family.
See you later.

**Comment by DrakMrak** [comment]
Hi
Ok lol kompliments  exchanged ;) thanks for accepted me into the group :)
Something about me: I working around GeoGet for Czech Cachers and I know team working... 
and mainly I'm working in Pascal and C# and a lot of SQL. Java is a lot of similar as C# ;) however, working in javascript and on the web is new to me
..
OK I prepare one switch for compact layout and some changes :) and make Issue for this thinks...
..
Merry christmass to you and your family too.
See you later.

**Comment by 2Abendsegler** [comment]
Hi DrakMrak,
seems to be good. If this are the complete changes, I will merge it and give it a Config parameter.
How can I name the parameter?
Suggestion: Show compact layout on new dashboard (variant DrakMrak)  :)
Thanks

**Comment by DrakMrak** [comment]
Hello Frank
still wait! lol
I've got it yet in progress, and some changes I will do it
And I try make config parametter for this changes:  **settings_compact_layout_new_dashboard**
I'm learning how to do it...

but there is holidays and free time so I'm going away a lot time, some cache, new year is close :) but I work when it's time for it (slowly).
I wish you nice holidays...
DrakMrak

**Comment by 2Abendsegler** [comment]
Ok. :)
Also nice holidays.

**Comment by DrakMrak** [comment]
Hello Frank
I have made some changes just now but that I do not know exactly how it is with the conflicts...

**Comment by 2Abendsegler** [comment]
Hello,

the conflicts coming because of changes are just done at the same programm places of your changes. I am guilty. :) I have done some bigger changes on the dashboard and other routines. Some of them needed another place below the VIP VUP processing to run correctly.
Conflicts are not often available, only if we tinker on same programm places. 

I can remedy the conflicts manually by merging process, but the consequence could be that your changes, the number of commits and the number of changing lines, will be credited to my account and not to yours. That's GitHub.

So my suggestion in such cases is always the same. Save a backup of your GClh on your account. Then rebase your folk or make a new folk. After this you have to build in your changes again and make a pull request.

Cheers

**Comment by DrakMrak** [comment]
Ok I understand :)

**Comment by 2Abendsegler** [comment]
Me again.
I think you have to try to copy the GClh or parts of it from my account to yours, perhaps to eliminate the conflicts. But this is not the rights way. You should only done a rebase or a new folk, because GitHub do not know manually transfers and can not determine the exact changes. :)

**Pull request closed without merging**
