### PR TITLE
Rewrite fixed PQ header/footer by pure CSS. Compatible with compact view

### PR DESCRIPTION
**Pull request by Dratenik**
Make header and footer for PQ fixed position, so this is displayed on small monitor.
Here is PR to collector brach as you requered in https://github.com/2Abendsegler/GClh/pull/1033

### CODE REVIEW

**Comment by Ruko2010** [comment]
If it helps: This is my Config for the PQ-View:
image

**Comment by Dratenik** [comment]
> The Header has a little (1px?) gap to the browsers edge.
I see it in Chrome. Fixed this by added "-1px" to position. Please check "if (browser === "edge")" work correctly. It is not used anywhere. I don't own the Edge browser, sorry.

> The footer is not fixed on my PC.
I think that is same bug as header. I applied position to table cell, it will help.

**Comment by Ruko2010** [comment]
Hello @Dratenik it is working now on Chrome, thanks for the fix. Two more things:
1. `if (browser === "chrome" || browser === "edge") {
                positionPx = -1; // Mitigate ugly gap for header/footer
              }
`
will not work, because we only distinguish between Chrome and FF. I also have no Edge Browser because I'm a Mac User, so I can't test this. Maybe @2Abendsegler can test it.

2. Please change the variable from
`c.settings_fixed_pq_header = getValue("settings_fixed_pq_header", true);`
back to
`c.settings_fixed_pq_header = getValue("settings_fixed_pq_header", false);`
Users can activate the feature via the config.

I'm on vacation for the next 3 weeks, so don't expect an answer from me in this time. But if you implement the 2 things, I'll publish the feature in the next release.
@2Abendsegler You can do the merge If you like and have the time for it.

**Comment by Dratenik** [comment]
> will not work, because we only distinguish between Chrome and FF

You are right. Edge browser is not detected. Fortunately, it is not needed. I tried the function in version Edge 18 (in a virtual box) and displayed normally without a 1px gap. Now I see it confused. In your comment https://github.com/2Abendsegler/GClh/pull/1035#pullrequestreview-240412800 you write "browsers edge" and you mean "browsers' window border" not Edge as browser. It's funny.

> Users can activate the feature via the config.

Ok, but it's a shame. I think it's a non-invasive useful feature for everyone.

**Comment by Ruko2010** [comment]
> In your comment [#1035 (review)](https://github.com/2Abendsegler/GClh/pull/1035#pullrequestreview-240412800) you write "browsers edge" and you mean "browsers' window border" not Edge as browser. It's funny.

Sorry for the confusion. English is not my native language 😃

> Ok, but it's a shame. I think it's a non-invasive useful feature for everyone.

I thought about it again and you are right. Make it a default option.

**Comment by Dratenik** [comment]
> I thought about it again and you are right. Make it a default option.
Sorry for the delay. Set as you wish.

**Comment by Ruko2010** [comment]
No Problem. I'll check the feature again and it will be published in the next version.

**Pull request merged**
