### PR TITLE
Issue/865 Insert new preview map for cache listing and PQ settings

### PR DESCRIPTION
**Pull request by CachingFoX**
@Ruko2010 please can you review my changes.

Especially these two changes:
AccessToken: https://github.com/CachingFoX/GClh/commit/89115e5abacb4ad7083b890c194e295ffd3e77a5
InjectPageScript: https://github.com/CachingFoX/GClh/commit/7601b2b98f8b6d0004502934d89f6a0814261d91

Last modification can be very critical, because the function is used on several parts in the script.

### CODE REVIEW

**Comment by CachingFoX** [comment]
@Ruko2010 Additional information can be found in the bug issue https://github.com/2Abendsegler/GClh/issues/865, please read it.

**Comment by Ruko2010** [comment]
@CachingFoX I'll review your changes, but I'm in Hamburg for the rest of the week, so it will be not earlier than next week.

**Comment by Ruko2010** [comment]
@CachingFoX ich habe es leider nicht geschafft es zu reviewen. Vielleicht kann @2Abendsegler das übernehmen.
Ich bin ab Samstag erstmal 3 Wochen im Urlaub. Da ich weder einen Rechner mit habe, noch damit rechne überhaupt Internet zu haben, werdet ihr erstmal nichts von mir hören 😉.

**Comment by Ruko2010** [comment]
I checked and everything seams to look good. I tested with FF and Chrome, both on my Mac. I'll put it in the collector to evaluate it in the daily use.

**Pull request merged**
