### PR TITLE
[Drafts] Statistic of cache types and log types and mark double caches

### PR DESCRIPTION
**Pull request by capoaira**
#2089

Ich habe alles mit meinen 25 Drafts getestet. Das funktioniert. Aber mit mehr konnte ich noch nicht testen.
Ich denke wir beide sollten die Funktion testen und noch abwarten, bis einer von uns so 50-100 oder mehr zum Testen zur Verfügung hat.

### CODE REVIEW

**Comment by RubyShoos** [comment]
I am really excited about this development. My logging queue is a disaster (i.e. way too long) at the moment, so this will help make some sense of it. 

I tried to use the link to install the temporary version, but it just when I hit the 'Reinstall' button it just goes to a blank page and does not seem to update the version I am running. 

It's not a biggie and I REALLY appreciate you working on this, just keen to benefit from it :-D

Thank you! RubyShoos

**Comment by capoaira** [comment]
> I tried to use the link to install the temporary version, but it just when I hit the 'Reinstall' button it just goes to a blank page and does not seem to update the version I am running.

The normal behavior is that the tab closes (but this doesn't always work and is a bug of Tampermonkey)
The version number should not be updated, but you will still get the temporary development version. ;) Try opening the Drafts page. A "Count cache and log types" button should appear.

>It's not a biggie and I REALLY appreciate you working on this, just keen to benefit from it :-D

If you have so many Drafts, it would be very useful for us to know if it works. How many Drafts do you have?

**Comment by RubyShoos** [comment]
Perfect - it seems to work perfectly (without counting every log type - the numbers look about right). I was looking for the  "Count cache and log types" on the GClh II Config page - I didn't even look for it on the Drafts page - doh! It appears as a link rather than a button, but once you are looking for it, it's perfectly obvious. 

At the moment I have 412 caches in the queue. And it seemed to handle them well, loading up the full page until it reached the bottom (which took about 7 seconds), then produced the output in the screenshot below.

Just in terms of feedback, 'Found It' (394 count) and 'Attended' (4 count) look identical, but I know what is what.

I have tried uploading the screenshot, lets see...

Again, thank you for this utterly brilliant addition to the new Drafts page - very excited to be back in touch with my 'Pending'  data!

2022-05-01 18_51_04-Drafts — Mozilla Firefox

**Comment by 2Abendsegler** [comment]
@RubyShoos 
Great test example. 😀

@capoaira 
Looks great.

Can you maybe reduce the space between the numbers and the next cache type?
And maybe you could add a separator between the cache types and the log types, something like " | "?

Then I will test briefly, also because of the double. @RubyShoos has already done the main test. 😀

**Comment by capoaira** [comment]
> And maybe you could add a separator between the cache types and the log types, something like " | "?

If you not have as many Drafts, the separator looks a bit stupid 😅
grafik

**Comment by 2Abendsegler** [comment]
> If you not have as many Drafts, the separator looks a bit stupid 😅

Stimmt 😂
Ich wusste nicht das die Log Types hinten ausgerichtet sind. Ich hatte ja noch nicht getestet. Mach das wieder weg und dann approve ich das Teil. 😀

**Comment by capoaira** [comment]
Zwischenräume sind nun etwas kleiner ;)

**Review by 2Abendsegler — COMMENTED** [review]
Looks great!

Just one small thing, RubyShoos had already noticed it and I think your screenshot shows it too. Isn't an attended at an event a different symbol than the smiley?

**Pull request merged**
