### PR TITLE
 Added a new function: active select date into geocaches and travelbugs calendar

### PR DESCRIPTION
**Pull request by Dratenik**
Did you ever browse the calendar? Year or two back? GC provides scrolling by only one month. Very slow browsing.

This new feature adds two selections to the calendar. You can quickly select a year or a month.

Here is result: 
calendar_with_active_select

### CODE REVIEW

**Comment by GFEMajor** [comment]
@2Abendsegler do you think we need a config parameter for this option? This is nothing that "destroys" old functionality, only adds a shortcut. I would add this feature without a switch.

**Comment by 2Abendsegler** [comment]
Yes, a switch should be not necessary.

**Comment by Dratenik** [comment]
Hi,

> We work with intends of 4 spaces, not with tab.

Have you ever heard of the formatting rules? It would be great if you provided them and followed them in your project. I do not agree that the gaps are better than the tab, but I will subordinate myself. I have replaced all the tabs in the file. There were more that only my code. See https://github.com/Dratenik/GClh/commit/1b6dfa237d13a8c4eaf0de5ad6c545a7e7cbc1ef

>  You have entered some additional empty lines at the end of the code.

Ok, sorry for this. I do not know how they got there. They are gone.

> This should not be necessary. Can you please delete them again. Function is_link is a main function. 

I do not know how else to know I'm on a specific URL. Preserved it.

> This is nothing that "destroys" old functionality, only adds a shortcut. I would add this feature without a switch.

Ok, configuration is deleted. See https://github.com/Dratenik/GClh/commit/c872876db34d3baa30555aeeee3443cca3053775#diff-53d8e754dbddfc58e7cf268ba997aefa

>  Can you please implement your main coding in front of "Show warning for not available images" at about line 6409. This should be a better place.

I'm sorry, but I do not understand what you want. You means move my line before 6409?

Cheers,
Dratenik

**Comment by 2Abendsegler** [comment]
Thank you for the changes.

Yes I meant move your lines before 6409? Sorry it was my bad english. But we do it now like in the most cases, because nobody can know where the best place is in our opinion. ;)

Normaly we change also the tabs, but because we have not only this points, I took it into the change request. I have seen that there are some other tabs and changed the tabs just for v0.9.1. Sometimes we overlook some.
We have some formatting rules but only in german and perhaps not at the right place. We will talk about it in our group.

Can you please describe where the main coding comes from? I have to check it because of our license agreement before I can implement it.

I will check your changes today or tomorrow.
You are welcome.
Cheers.

**Comment by Dratenik** [comment]
Hi,

> Yes I meant move your lines before 6409?

Ok, I move it in https://github.com/Dratenik/GClh/commit/9e86438ccf00a638e33c95407f2a923e52f26fd3 .

> We have some formatting rules but only in german and perhaps not at the right place.

It might be a good idea to save the Eclipse format file into the repository. It's one XML file and it's been accepted by many editors. Here is tutorial: https://www.ibm.com/developerworks/opensource/tutorials/os-eclipse-code-templates/index.html

> Can you please describe where the main coding comes from?

It's my own code and it's published by GNU General Public License v2.0.

> You have forgotten to build back function is_link. 

I did not forget. I do not know what a better way to check which page is currently displayed.

Cheers,
Dratenik

**Comment by 2Abendsegler** [comment]
You can check which page is currently displayed direct in your main coding, or does something speak against this?

**Comment by Dratenik** [comment]
> You can check which page is currently displayed direct

Ok, if you mean that is better way here is: https://github.com/Dratenik/GClh/commit/109f9b34df981f4a9cde6a1cf5395fd65d1ad76a

Cheers,
Dratenik

**Pull request merged**
